#!/bin/bash

# directory of lumass executable
DIR=$1
LUMASS_VERSION=$2 #0.9.32


# locate and copy lumass dependencies into install tree
# for distribution; we accept that some libs are tried
# to be copied more that once which will give a warning
# that the lib already exist and won't be copied again,
# so no harm done - just ignore admittledly ugly warnings ...

#
cd $DIR

# copy lumass depencies
cp $( ldd lumass | cut -d " " -f 3) ../lib/

# add platform specific libqxcb.so to file tree
mkdir platforms
cp $( locate libqxcb.so ) platforms/
# also add all dependencies of libqxcb.so to lib dir in distr. tree
cp $( ldd platforms/libqxcb.so | cut -d " " -f 3) ../lib/

# need this one as well, so just copy it
cp $( locate libQt5DBus.so ) ../lib/

# also need to copy gdal kea plugin
cp $( locate libkea.so ) ../lib/
cp $( locate gdal_KEA.so) ../lib/

# package ...
cd ../../

OS=$( uname -s )
REL=$( uname -r )
PLATFORM=$( uname -i )

tar czvf lumass-$( echo $LUMASS_VERSION )_$OS-$( echo $REL )_$PLATFORM.tar.gz lumass
